#LIBRARIES
INCLUDE_DIRECTORIES(${PROJECT_SOURCE_DIR}/extern/cccl/thrust)

#EIGEN3
FIND_PACKAGE(Eigen3 QUIET REQUIRED)
INCLUDE_DIRECTORIES(${EIGEN3_INCLUDE_DIR})

#OpenMP
FIND_PACKAGE(OpenMP REQUIRED)
IF(OPENMP_FOUND)
  SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
  SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
ENDIF(OPENMP_FOUND)

#Cuda
IF(NOT CUDA_TOOLKIT_ROOT_DIR)
  SET(CUDA_TOOLKIT_ROOT_DIR "/usr/local/cuda")
ENDIF()
FIND_PACKAGE(CUDA QUIET REQUIRED)
IF(CUDA_FOUND)
  INCLUDE_DIRECTORIES(${CUDA_INCLUDE_DIRS})
  MESSAGE(STATUS "Found CUDA @ ${CUDA_INCLUDE_DIRS}")
  LIST(APPEND ALL_LIBRARIES ${CUDA_LIBRARIES} ${CUDA_cublas_LIBRARY} ${CUDA_cusolver_LIBRARY})
  ADD_DEFINITIONS(-DWITH_CUDA)
ELSE(CUDA_FOUND)
  MESSAGE(SEND_ERROR "Cannot find CUDA, compiling without it!")
ENDIF(CUDA_FOUND)

#GLFW
FIND_PACKAGE(GLFW QUIET REQUIRED)
INCLUDE_DIRECTORIES(${GLFW_INCLUDE_DIR})
LIST(APPEND ALL_LIBRARIES ${GLFW_LIBRARY})

#TinyVisualizer
ADD_DEFINITIONS(-DIMGUI_SUPPORT)
ADD_DEFINITIONS(-DIMGUI_IMPL_OPENGL_LOADER_GLAD2)
FILE(GLOB IMGUI
  ${PROJECT_SOURCE_DIR}/extern/TinyVisualizer/extern/imgui/*.h
  ${PROJECT_SOURCE_DIR}/extern/TinyVisualizer/extern/imgui/*.cpp
  ${PROJECT_SOURCE_DIR}/extern/TinyVisualizer/TinyVisualizer/imgui/*.h
  ${PROJECT_SOURCE_DIR}/extern/TinyVisualizer/extern/imgui/backends/imgui_impl_glfw.h
  ${PROJECT_SOURCE_DIR}/extern/TinyVisualizer/extern/imgui/backends/imgui_impl_glfw.cpp
  ${PROJECT_SOURCE_DIR}/extern/TinyVisualizer/extern/imgui/backends/imgui_impl_opengl3.h
  ${PROJECT_SOURCE_DIR}/extern/TinyVisualizer/extern/imgui/backends/imgui_impl_opengl3.cpp)
INCLUDE_DIRECTORIES(${PROJECT_SOURCE_DIR}/extern/TinyVisualizer/extern/glad/include)
INCLUDE_DIRECTORIES(${PROJECT_SOURCE_DIR}/extern/TinyVisualizer/extern/imgui)
INCLUDE_DIRECTORIES(${PROJECT_SOURCE_DIR}/extern/TinyVisualizer/extern)
MACRO(SEARCH_SOURCE NAME DIRPRJ)
  FILE(GLOB_RECURSE header${NAME} ${PROJECT_SOURCE_DIR}/${DIRPRJ}/*.h ${PROJECT_SOURCE_DIR}/${DIRPRJ}/*.hpp ${PROJECT_SOURCE_DIR}/${DIRPRJ}/*.hh ${PROJECT_SOURCE_DIR}/${DIRPRJ}/*.cuh)
  FILE(GLOB_RECURSE source${NAME} ${PROJECT_SOURCE_DIR}/${DIRPRJ}/*.cpp ${PROJECT_SOURCE_DIR}/${DIRPRJ}/*.cc ${PROJECT_SOURCE_DIR}/${DIRPRJ}/*.c ${PROJECT_SOURCE_DIR}/${DIRPRJ}/*.cu)
ENDMACRO(SEARCH_SOURCE)
SEARCH_SOURCE(TinyVisualizer extern/TinyVisualizer/TinyVisualizer)
SEARCH_SOURCE(GLAD extern/TinyVisualizer/extern/glad/src)
SEARCH_SOURCE(ImGui extern/TinyVisualizer/extern/imgui)
ADD_LIBRARY(TinyVisualizer STATIC
    ${headerTinyVisualizer} ${sourceTinyVisualizer}
    ${headerGLAD} ${sourceGLAD}
    ${IMGUI} ${IMGUI})
